---
title: "sph 112 measles project"
output: html_document
date: "2026-04-27"
---

```{r}
library(tidyverse)
library(readxl)
library(ggplot2)
library(janitor)
```
## Data Import
```{r}
measles_case_records <- read_xlsx("Utopia_Measles_Dataset.xlsx", "Measles_Case_Records")
annual_trend_2010_2015 <- read_xlsx("Utopia_Measles_Dataset.xlsx", "Annual_Trend_2010_2025")
outbreak_detail <- read_xlsx("Utopia_Measles_Dataset.xlsx", "Outbreak_Detail")
sspe_registry <- read_xlsx("Utopia_Measles_Dataset.xlsx", "SSPE_Registry")
vaccination_coverage <- read_xlsx("Utopia_Measles_Dataset.xlsx", "Vaccination_Coverage")
public_opinion_survey <- read_xlsx("Utopia_Measles_Dataset.xlsx", "Public_Opinion_Survey")
county_geographic_summary <- read_xlsx("Utopia_Measles_Dataset.xlsx", "County_Geographic_Summary")
given_summary_statistics <- read_xlsx("Utopia_Measles_Dataset.xlsx", "Summary_Statistics")
```

## Vaccine opinion by county
```{r}
county_geographic_summary <- clean_names(county_geographic_summary)
county_geographic_summary

```

```{r}
county_geographic_summary |> 
  select(county, pct_pro_vaccine_attitude, pct_vaccine_hesitant) |> 
  pivot_longer(cols = c(pct_vaccine_hesitant, pct_pro_vaccine_attitude),
               names_to = "attitude",
               values_to = "percent") |> 
  ggplot(aes(x = reorder(county, percent, decreasing = T), y = percent, fill = attitude))+
  geom_col(position = "dodge") +
  scale_fill_discrete(labels = c("pct_vaccine_hesitant" = "Vaccine Hesitant",
                                 "pct_pro_vaccine_attitude" = "Pro Vaccine"))+
  coord_flip() +
  labs(y = "Percent of Population", 
       x = "County", 
       fill = "Vaccine Attitude",
       title = "Vaccine Attitudes by County") 

## Need to add anti-vax as a category maybe
```
## Vaccine coverage disparities

```{r}
unvax_individual_demographics<- vaccination_coverage |> 
  select(County, Urban_Rural, SES_Category, Insurance_Type, Age_Years, Race_Ethnicity, MMR_Vaccination_Status, Vaccine_Exemption_Type, Reason_if_Unvaccinated, Provider_Recommended_MMR, Received_MMR_at) |> 
  filter(!is.na(Reason_if_Unvaccinated))
```
```{r}
unvax_individual_demographics
#vacc coverage has like 2000 entries but total cases is like 308
```

```{r}
unvax_individual_demographics |> 
  count(Reason_if_Unvaccinated, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```

```{r}
unvax_individual_demographics |> 
  filter(Reason_if_Unvaccinated == "Cost") |> 
  count(Race_Ethnicity, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```

```{r}
measles_case_records |> 
  count(Race_Ethnicity, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```


# kinda unclear the number of ppl in each race just given percents
#total pop of utopia: 310000 (from excel)
#white non hisp = 75.1% 
#black = 1.4%
# native = 5.7%
# asian = 1.4%
# pacific islander = 0.4%
# multiracial = 4.6%
#hispanic = 15.8%
# adds up to 104.4 % though?


```{r}
measles_case_records |> 
  count(Insurance_Type) |> 
  mutate(percentage = n / sum(n) *100) |> 
  arrange(desc(percentage))
```

```{r}
measles_case_records |> 
  count(SES_Category, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```
```{r}
measles_case_records |> 
  group_by(County, SES_Category) |> 
  summarise(n = n(), .groups = "drop") |> 
  group_by(County) |> 
  mutate(pct = n / sum(n) * 100)

```

```{r}
measles_case_records |> 
  count(Vaccination_Status, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```
```{r}
vaccination_coverage |> 
  filter(Age_Years <= 2.92) |> 
  count(MMR_Vaccination_Status, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```
# Public opinion vaccine categories

```{r}
#In presentation state the cut offs for each vaccine attitude category
anti_vax_opinion_survey<- public_opinion_survey |> 
  filter(Vaccine_Attitude_Category == "Anti-vaccine")
  
```
```{r}
vax_hesitant_opinion_survey<- public_opinion_survey |> 
  filter(Vaccine_Attitude_Category == "Vaccine-hesitant")
```
```{r}
pro_vax_opinion_survey<- public_opinion_survey |> 
  filter(Vaccine_Attitude_Category == "Pro-vaccine")
```

#Anti-vax
```{r}
anti_vax_opinion_survey |> 
  count(Education_Level, sort = T) 
```
```{r}
anti_vax_opinion_survey |> 
  count(Info_Source_Primary, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```

```{r}
anti_vax_opinion_survey |> 
  count(Believes_MMR_Causes_Autism, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```
```{r}
anti_vax_opinion_survey |> 
  summarise(across(where(is.numeric), mean, na.rm = TRUE))
```
```{r}
anti_vax_opinion_survey |> 
  count(Children_Up_to_Date_on_Vaccines, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```

#Vax-hesitant

```{r}
vax_hesitant_opinion_survey |> 
  summarise(across(where(is.numeric), mean, na.rm = TRUE))
```
```{r}
vax_hesitant_opinion_survey |> 
  count(Education_Level, sort = T) 
```
```{r}
vax_hesitant_opinion_survey |> 
  count(Info_Source_Primary, sort = T)
```
```{r}
vax_hesitant_opinion_survey |> 
  count(Believes_MMR_Causes_Autism, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```
```{r}
vax_hesitant_opinion_survey |> 
  count(Children_Up_to_Date_on_Vaccines, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```
# Pro-vax

```{r}
pro_vax_opinion_survey |> 
  summarise(across(where(is.numeric), mean, na.rm = TRUE))
```
```{r}
pro_vax_opinion_survey |> 
  count(Education_Level, sort = T) 
```
```{r}
pro_vax_opinion_survey |> 
  count(Info_Source_Primary, sort = T)
```
```{r}
pro_vax_opinion_survey |> 
  count(Believes_MMR_Causes_Autism, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```
```{r}
pro_vax_opinion_survey |> 
  count(Children_Up_to_Date_on_Vaccines, sort = T) |> 
  mutate(percentage = n / sum(n) *100)
```